# Generated by Django 5.0 on 2025-09-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('cash_flow', models.JSONField()),
                ('income_statement', models.JSONField()),
                ('balance_sheet', models.JSONField()),
                ('profitability', models.JSONField()),
            ],
        ),
    ]
